import os


SECRET_KEY = os.getenv('SECRET_KEY')
ENV = os.getenv('ENV')

ALLOWED_ORIGINS = [host for host in os.getenv('ALLOWED_ORIGINS').split(';')]
ALLOWED_ORIGINS_REGEX = os.getenv('ALLOWED_ORIGINS_REGEX')

AZURE_VLTSTORAGESERVICE1_DOMAIN = os.getenv('AZURE_VLTSTORAGESERVICE1_DOMAIN')
AZURE_VLTSTORAGESERVICE1_CONNECTION_STRING = os.getenv(
    'AZURE_VLTSTORAGESERVICE1_CONNECTION_STRING')
AZURE_VLTSTORAGESERVICE1_CONTAINER = os.getenv(
    'AZURE_VLTSTORAGESERVICE1_CONTAINER')
DJANGO_CONTENT_TYPE_ID_BASE_API = os.getenv('DJANGO_CONTENT_TYPE_ID_BASE_API')
DJANGO_CONTENT_TYPE_ID_BASE_FASTAPI_API = os.getenv(
    'DJANGO_CONTENT_TYPE_ID_BASE_FASTAPI_API')

COSMOS_CONNECTION_STRING = os.getenv('COSMOS_CONNECTION_STRING')
COSMOS_KEY = os.getenv('COSMOS_KEY')
COSMOS_BASE_FASTAPI_DATABASE = os.getenv('COSMOS_BASE_FASTAPI_DATABASE')
COSMOS_BASE_FASTAPI_AUDIT_LOG_CONTAINER = os.getenv('COSMOS_BASE_FASTAPI_AUDIT_LOG_CONTAINER')

SB_CONNECTION_STR = os.getenv('SB_CONNECTION_STR')
SB_EMAIL_QUEUE = os.getenv('SB_EMAIL_QUEUE')
SB_MAX_WAIT_TIME = os.getenv('SB_MAX_WAIT_TIME')
SB_MESSAGES_TO_READ = os.getenv('SB_MESSAGES_TO_READ')

DB_PORT = os.getenv('DB_PORT')
DB_HOST = os.getenv('DB_HOST')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_NAME = os.getenv('DB_NAME')
DB_NAME_ASSET = os.getenv('DB_NAME_ASSET')
DB_USER = os.getenv('DB_USER')
DB_NAME_BASE_API = os.getenv('DB_NAME_BASE_API')
DB_NAME_VOLTALIADB1 = os.getenv('DB_NAME_VOLTALIADB1')
DB_NAME_USERS = os.getenv('DB_NAME_USERS')

SMTP_FROM_EMAIL = os.getenv('SMTP_FROM_EMAIL')
SMTP_EMAIL_HOST = os.getenv('SMTP_EMAIL_HOST')
SMTP_EMAIL_PORT = os.getenv('SMTP_EMAIL_PORT')
SMTP_EMAIL_HOST_PASSWORD = os.getenv('SMTP_EMAIL_HOST_PASSWORD')

ANALYTICS_APPLICATION_USER = os.getenv('ANALYTICS_APPLICATION_USER')
ANALYTICS_APPLICATION_PASSWORD = os.getenv('ANALYTICS_APPLICATION_PASSWORD')
ANALYTICS_LOGIN_ROUTE = os.getenv('ANALYTICS_LOGIN_ROUTE')

SHAREPOINT_DOMAIN = os.getenv('SHAREPOINT_DOMAIN')
SHAREPOINT_SITE_COMMON_URL = SHAREPOINT_DOMAIN + \
    os.getenv('SHAREPOINT_SITE_COMMON_URL')
SHAREPOINT_USERNAME = os.getenv('SHAREPOINT_USERNAME')
SHAREPOINT_PASSWORD = os.getenv('SHAREPOINT_PASSWORD')
SHAREPOINT_RRV_ACR_FILES_DIRECTORY = os.getenv(
    'SHAREPOINT_RRV_ACR_FILES_DIRECTORY')

DJANGO_CONTENT_TYPE_ID_BASE_FASTAPI_API = os.getenv(
    'DJANGO_CONTENT_TYPE_ID_BASE_FASTAPI_API')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
BASE_FASTAPI_FRONTEND_URL = os.getenv('BASE_FASTAPI_FRONTEND_URL')
